#pragma once
#ifndef _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS_CLASS
#define _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS_CLASS

#define _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS
#define _SILENCE_CXX20_CISO646_REMOVED_WARNING
#include "physx/PxPhysics.h"
//#include "Bullet3/btBulletDynamicsCommon.h"

#endif 